title: endoflife.date
description: >- # this means to ignore newlines until "baseurl:"
  Check End of Life of php, python, ubuntu, alpine, laravel, debian etc at one place.
  Verify whether your application needs an update, or if you need to upgrade your device.
baseurl: ""
url: "https://endoflife.date" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-timeago

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

jekyll_timeago:
  depth: 2
