php:
  url: https://www.php.net/supported-versions.php
  releases:
    '7.1':
      release: 2016-12-01
      eol: 2019-12-01
      support: 2018-12-01
      current: 7.1.29
    '7.2':
      release: 2017-11-30
      eol: 2020-11-30
      support: 2019-11-30
      current: 7.2.18
    '7.3':
      release: 2018-12-06
      eol: 2021-12-06
      support: 2020-12-06
      current: 7.3.5
laravel:
  url: https://laravel.com/docs/5.8/releases#support-policy
  releases:
    '5.5':
      release: 2017-08-30
      support: 2019-08-30
      eol: 2020-08-30
      current: 5.5.45
      lts: true
    '5.7':
      release: 2018-09-04
      support: 2019-03-04
      eol: 2019-09-04
      current: 5.7.28
    '5.8':
      release: 2019-02-26
      support: 2019-09-26
      eol: 2020-02-26
      current: 5.8.18
python:
  releases:
    '3.7':
      release: 2018-06-27
      eol: 2023-06-27
      current: 3.7.3
    '3.6':
      release: 2016-12-23
      eol: 2021-12-23
      current: 3.6.8
    '2.7':
      release: 2010-07-03
      eol: 2020-01-01
      current: 2.7.16
    '3.5':
      release: 2015-09-13
      eol: 2020-09-13
nodejs:
  url: https://nodejs.org/en/about/releases/
  releases:
    v10:
      release: 2018-04-24
      lts: 2018-10-30
      support: 2020-04-01
      eol: 2021-04-01
    v12:
      release: 2019-04-23
      lts: 2019-10-22
      support: 2021-04-01
      eol: 2021-04-01
    v14:
      release: 2020-04-21
      lts: 2020-10-20
      support: 2022-04-01
      eol: 2023-04-01
ubuntu:
  url: https://wiki.ubuntu.com/Releases
  releases:
    19.04:
      release: 2019-04-18
      support: 2020-01-01
      eol: 2020-01-01
    18.10:
      release: 2018-10-18
      support: 2019-07-01
      eol: 2019-07-01
    18.04:
      release: 2018-04-26
      support: 2023-04-01
      eol: 2028-04-01
      current: 18.04.2
    16.04:
      release: 2018-04-21
      support: 2021-04-01
      eol: 2024-04-01
      current: 18.04.6
    14.04:
      release: 2014-04-17
      support: 2019-04-01
      eol: 2022-04-01
      current: 18.04.6
alpine:
  url: https://wiki.alpinelinux.org/wiki/Alpine_Linux:Releases
  releases:
    v3.9:
      release: 2019-01-29
      current: v3.9.4
      eol: 2021-01-01
      support: true
    v3.8:
      release: 2018-06-26
      current: v3.8.2
      support: true
    v3.7:
      release: 2017-11-30
      current: v3.7.0
      support: true
      eol: 2019-11-01