
alpine:
  url: https://wiki.alpinelinux.org/wiki/Alpine_Linux:Releases
  releases:
    v3.9:
      release: 2019-01-29
      current: v3.9.4
      eol: 2021-01-01
      support: true
    v3.8:
      release: 2018-06-26
      current: v3.8.2
      support: true
    v3.7:
      release: 2017-11-30
      current: v3.7.0
      support: true
      eol: 2019-11-01
